language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install bison gperf; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install rake bison git gperf; fi
before_script:
  - git clone https://github.com/mruby/mruby.git
script:
  - rake all test
