name: Build Website and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build Website and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        run: |
          cd website
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/out
          CLEAN: true