name: Build Website and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build Website and Deploy
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install Gem dependencies
        run: gem install yard yard-mruby
      - name: Build
        run: |
          cd website
          npm ci
          npm run build
          touch out/_next/.nojekyll

      - name: Generate Docs
        run: |
          rake docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/out
          CLEAN: true
