name: Test Website Build
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Test Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install Gem dependencies
        run: gem install yard yard-mruby
      - name: Build
        run: |
          cd website
          npm ci
          npm run build
      - name: Generate Docs
        run: |
          rake docs