name: Test Website Build
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        run: |
          cd website
          npm ci
          npm run build